service: yunzhong
runtime: python
env: flex
api_version: 1
threadsafe: yes
entrypoint: python3 Y_Runtime.py

runtime_config:
  python_version: 3


handlers:
- url: .*
  script: Y_Runtime.py
  
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 20
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 2

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.5
    
    